### ISSUE TITLE
Error when run create-bridge command for iOS/Objective-C

### ISSUE THREAD

**Issue by danielfeelfine** [peggyrayzis/react-native-create-bridge#14]
`
Error: ENOENT: no such file or directory, open '.../ios/ExampleBridge.h'
`

**Comment by peggyrayzis** [comment]
Thanks for reporting! Can you please provide a little more context? Were you running the command in an existing RN project?

**Comment by danielfeelfine** [comment]
I was running out of the project. Problem solved. Thanks :)
