### ISSUE TITLE
Convert to a plugin

### ISSUE THREAD

**Issue by grabbou** [peggyrayzis/react-native-create-bridge#19]
Changing this project to a `react-native` plugin, would mean that after installing it locally into project dependencies, you can run `react-native create-bridge` instead of having global executable.

Would be easier to version, adapt to breaking react-native changes and work across projects.

Since this is not a super documented feature, I would love to send a PR adding this.

Would you be / other users open to having such workflow instead?

**Comment by peggyrayzis** [comment]
I absolutely love this idea and would gladly accept a PR! I didn't even know custom plugins were an option so thank you so much for suggesting this.

I'm going to post on Twitter to see if anyone has any objections, although I don't think anyone will 😀

**Comment by andrerfneves** [comment]
I think this is a better approach. Would love to help work on this PR but am not super familiar with custom plugins in RN. Given that @grabbou worked on the initial port of RNPM -> `react-native link` plugin I'm assuming he has a lot of insight in there.

**Comment by grabbou** [comment]
@andrerfneves I am busy in upcoming days (travelling), so I am happy to help you as much as I can to land this!

To start - it's really simple. React Native CLI has a built-in mechanism for detecting plugins. In order to be detected as a plugin, your package has to meet the following criteria:
- it has to start with `react-native-*`
- it has to be present in `package.json` of `react-native` project
- it has to include `rnpm.plugin` key in `package.json`, that points to a `main` plugin file, e.g.:
```json
{
  "rnpm": {
     "plugin:" "./src/abc.js",
  }
}
```
path is resolved relatively to the directory.

The plugin entry file (in our context - src/abc.js) has to be a file with `module.exports` that is either an object or an array of objects.

Here's such object for `bundle` command -> https://github.com/facebook/react-native/blob/master/local-cli/bundle/bundle.js#L29-L33

In order to test it, you can just `npm link` your package to the testing react-native project. Don't forget to add it to `package.json` dependencies.

**Comment by andrerfneves** [comment]
@grabbou this sounds great! I've got a couple deliverables towards the end of the week that need to be met, but I will try and get this going sometime this week/early next week. @peggyrayzis whenever I start, I'll push a branch out to the repo and raise a WIP pull request so that you can also contribute if you want to.

**Comment by grabbou** [comment]
Sounds good! Please CC me if you have any questions down the road! I'll be happy to answer and pair on whatever is needed to ship it :)

**Comment by peggyrayzis** [comment]
@grabbou thanks for the overview on building a custom plugin, this is super helpful!

@andrerfneves thank you for taking this on, I really appreciate it! I'm looking forward to reviewing your PR. Please let me know if you have any questions along the way! 😊

**Comment by peggyrayzis** [comment]
Hey @andrerfneves! 🙋 I wanted to check in and see how you're doing with the plugin PR. No worries if you haven't started it yet, just wanted to let you know I'm available for help if you need it!

**Comment by jarretmoses** [comment]
@andrerfneves I'd be down to tag team this with you. Would be a great addition / learning experience

**Comment by andrerfneves** [comment]
@jarretmoses let's do it. The more the merrier! @peggyrayzis hoping to have something up for you soon!! 👍

**Comment by peggyrayzis** [comment]
Welcome @jarretmoses! 🎉  It's great to have both of you on board to solve this issue, really excited to see your PR!

**Comment by jarretmoses** [comment]
@andrerfneves I got the ball rolling on this if you want to take a look https://github.com/jarretmoses/react-native-create-bridge/tree/feature/rn-plugin. From what I could tell the react native cli doesn't support async / await so a bunch of the work is just converting the functions to be promised based. However I may be mistaken but from reading through the source code and the errors being thrown from react native cli this did seem to be the case. I started the refactor and added the rnpm plugin path within the package.json and added the necessary module.exports as @grabbou suggested to the index.js. Also found this to be helpful https://github.com/facebook/react-native/blob/master/local-cli/core/findPlugins.js

**Comment by peggyrayzis** [comment]
Awesome, thanks Jarret! When you're ready, could you please submit a PR with your work? It can be work in progress (prefix with WIP in the PR title) - it's just easier for me to see the diff that way and give you feedback.

**Comment by andrerfneves** [comment]
@jarretmoses I'll start taking a look at this soon. Let's discuss in person first, think it'd help.

**Comment by jarretmoses** [comment]
@peggyrayzis will do. @andrerfneves sounds good

**Comment by jarretmoses** [comment]
Hey @peggyrayzis, any update here?

**Comment by jarretmoses** [comment]
@peggyrayzis is this being maintained anymore?

**Comment by aabanaag** [comment]
Any update on this? Would love to use this feature already.

**Comment by andrerfneves** [comment]
I don't believe this is priority enough for the maintainer nor is it going to get merged into this package.

**Comment by aabanaag** [comment]
@andrerfneves so we can use the repo of @jarretmoses for the mean time?

**Comment by andrerfneves** [comment]
@aabanaag we're speaking with the maintainer at the moment to be able to gain some Collaborator access in order to further development in the package. Stay tuned.

**Comment by jarretmoses** [comment]
Resolved https://github.com/peggyrayzis/react-native-create-bridge/pull/28
