### ISSUE TITLE
Remove createJSModules from packages of Android templates

### ISSUE THREAD

**Issue by peggyrayzis** [peggyrayzis/react-native-create-bridge#30]
This was a breaking change in RN v0.47.2. Not sure if overriding this method is necessary for native modules to work in earlier versions -- if so, we'll need to check the version in `package.json` and update the templates accordingly.

**Comment by peggyrayzis** [comment]
And the compiler fails if that method isn't overridden in earlier versions :( looks like we have to do the version check

**Comment by andrerfneves** [comment]
Had the same issue with `react-native-orientation`. It's a breaking change for Android. Anything above v0.47 needs to have it removed, otherwise it breaks compilation. Any project before v0.47 definitely needs the `@Override` call.
