### ISSUE TITLE
Error "Expected a component class, got [object Object]"

### ISSUE THREAD

**Issue by mosesmc52** [peggyrayzis/react-native-create-bridge#45]
Hi,

I installed the latest version of react-native-create-bridge (2.0.1) on react v 0.45.1. Following the steps as described in the [tutorial](https://www.youtube.com/watch?v=OrIIPNEjQfs&t=145s) posted by Peggy on youtube, I'm getting the error Expected a component class, got [object Object]. I'm not sure how to fix this error. 

Regards,

Moses

**Comment by jarretmoses** [comment]
@mosesmc52 could you give a little more context here? Are you saying you are following the tutorial and that some changes you made have broken something or is the command to generate the templates `react-native new-module` is not working. If it is the former I would say that is not necessarily an issue with this package. Let me know.

**Comment by mozilla-rowvigor** [comment]
It's the former. No sure it's an issue with the package. I'm following the tutorial. Made the exact changes as described in the tutorial up to @ 7:30  and experienced the error. The error occurs after I insert the generated rn created bridge js container HelloWorldSquare within the View container. 

I'm going to just use rn create bridge to generate the files and insert the container without editing and see if everything works. If everything works, I'll assume it's an inconsistency between what i'm doing and the tutorial.

**Comment by mozilla-rowvigor** [comment]
I created a new rn project, inserted the generated js container in the main view and experienced the same error.

**Comment by mozilla-rowvigor** [comment]
I figured out my own issue. The first letter of the name of the component must be capital.

**Comment by jarretmoses** [comment]
@mozilla-rowvigor That's great to hear. I'll keep that in mind as there's most likely an enhancement to the package to make sure that is the case.
