### ISSUE TITLE
Discuss: Change header search paths to look for header files in the Pods directory

### ISSUE THREAD

**Issue by peggyrayzis** [peggyrayzis/react-native-create-bridge#7]
Based on the [Shoutem team's experience](https://medium.com/shoutem/top-lessons-we-learned-while-building-a-react-native-bridge-library-bd6485cc6212#.4dpzsqen1) with react-native-create-bridge, they suggested configuring a default option to search for header files in the Pods directory when users are installing their SDKs with Cocoapods.

Here are some things I'd like to discuss before trying to implement:

- **Carthage vs. Cocoapods:** Does this process change if people are using Carthage to manage their dependencies? Would a project use both Carthage & Cocoapods? I'm not sure of best practices here. Ideally, I want create-bridge to make no assumptions about the user's setup.
- **How do we accomplish this programmatically?** It looks like they're setting this option in Xcode. If we can't accomplish this w/ code, then it's definitely an opportunity to improve the README.

**Comment by sirhotsauce** [comment]
Here's what I suggest for these two questions: 

1. Ask the user about his setup. This is how Yeoman generators do it and I've always liked it.

2. There is an npm package called xcode that let's you modify your XCode project. The RN team uses it for react-native link.

**Comment by peggyrayzis** [comment]
Thanks for your input Mihovil! That npm package is a good find 👍 

At this time, I'm going to hold off implementing this feature because it introduces added complexity. create-bridge was originally intended to be a "one size fits all" bridge generator. By implementing, we're making the assumption that the user is using a third-party SDK in their bridge, when they might just be implementing native functionality or linking an existing native view.

I'm going to keep this issue open and will revisit if more users request it.
